version: "3.6"
volumes:
  dap-postgres:
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION:-0.8}
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    # image: wurstmeister/kafka:latest
    image: debezium/kafka:${DEBEZIUM_VERSION:-0.8}
    hostname: kafka
    container_name: kafka
    ports:
      - target: 9092
        published: 9092
    depends_on:
      - zookeeper
    env_file:
      - ../environment/kafka/.default.env
      - ../environment/kafka/.${ENV}.env

  postgres:
    image: postgres:${POSTGRES_VERSION:-9.6}
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - ../environment/postgres/.default.env
      - ../environment/postgres/.${ENV}.env
    volumes:
      - ../scripts/postgres.entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ../scripts/postgres.install-plugins.sh:/docker-entrypoint-initdb.d/00-INSTALL-PLUGINS.sh
      - ../scripts/postgres.alter-role-set-search-path.sql:/docker-entrypoint-initdb.d/00-ALTER-ROLE-SET-SEARCH-PATH.sql
      - dap-postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    ports:
      - 8080:8080

  connect:
    image: debezium/connect:${DEBEZIUM_VERSION:-0.8}
    hostname: connect
    container_name: connect
    ports:
      - 8083:8083
    depends_on:
      - kafka
      - postgres
    environment:
      KAFKA_PORT_9092_TCP: 9092
    env_file:
      - ../environment/debezium-connect/.default.env
      - ../environment/debezium-connect/.${ENV}.env

  dap-data:
    # if it fails because of duplicate entry for in table g_flex_attrib_lov
    # run in local db `select setval('g_flex_attrib_lov_id_seq', max(id)+1, true) from g_flex_attrib_lov;`
    image: maven:3.5.2-jdk-8-slim
    hostname: dap-data
    container_name: dap-data
    volumes:
      - ${SERVICE_HOST_DIR}:/usr/src/app
      - ${HOME}/.m2:/root/.m2
    working_dir: /usr/src/app
    depends_on:
      - postgres
    links:
      - postgres:postgres
    environment:
      POSTGRES_DB: postgres
      SCHEMA: public
      STAGESCHEMA: dap_stg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT_5432_TCP: 5432
      POSTGRES_HOST_URL: postgres
    command: mvn spring-boot:run
    # logging:
    #   driver: "none"

  sbx:
    image: ashtr/devbox:ami
    hostname: sbx
    container_name: sbx
    command: '
      zsh -c "
      mkdir -p /root/.local/lib/python3.7/site-packages/certifi/;
      if [ ! -d /usr/src/workspace/gaws ]; then 
        git clone git@github.build.ge.com:healthcloud/gaws.git /usr/src/workspace/gaws;
      fi;
      if ! type gaws >/dev/null 2>&1; then
        echo \"\nalias gaws=\\\"python3 /usr/src/workspace/gaws/gaws.py\\\"\" >> ~/.bash_extras;
      fi;
      echo -e \"SBX Box is ready now\";
      tail -f /dev/null;
      "
    '
    env_file:
      - ../environment/docker/.default.env
      - ../environment/docker/.${ENV}.env
    volumes:
      - ${SERVICE_HOST_DIR}/:${APP_DIR}
      - ${HOME}/workspace:/usr/src/workspace
      - ${HOME}/.aws/credentials:/root/.aws/credentials
      - ${HOME}/.local/lib/python3.7/site-packages/certifi:/root/.local/lib/python3.7/site-packages/certifi
      - ${HOME}/.ssh/known_hosts:/root/.ssh/known_hosts
      - ${HOME}/.ssh/id_rsa:/root/.ssh/id_rsa
      - ${HOME}/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: ${APP_DIR}

  # dap-spring:
  #   container_name: dap-spring
  #   image: maven:3.5.2-jdk-8-slim
  #   command: >
  #     sh -c "ls; mvn clean install; mvn spring-boot:run"
  #   volumes:
  #     - ${HOME}/Spring-Kafka-ProducerConsumer:/usr/src/app
  #     - ${HOME}/.m2:/root/.m2
  #   working_dir: /usr/src/app
  #   depends_on:
  #     - kafka


  dap-notification-service:
    container_name: dap-notification-service
    image: maven:3.5.2-jdk-8-slim
    command: >
      sh -c "mvn spring-boot:run"
    env_file:
      - ../environment/docker/.default.env
      - ../environment/docker/.${ENV}.env
      - ../environment/dap-notification-service/.default.env
    volumes:
      - ${SERVICE_HOST_DIR}:/usr/src/app
      - ${HOME}/.m2:/root/.m2
    working_dir: /usr/src/app
    depends_on:
      - kafka
    links:
      - kafka:kafka
