-- CREATE DATABASE ${POSTGRES_DB};
\c
${POSTGRES_DB};

CREATE SCHEMA
IF NOT EXISTS ${SCHEMA} AUTHORIZATION ${POSTGRES_USER};
CREATE SCHEMA
IF NOT EXISTS ${STAGESCHEMA} AUTHORIZATION ${POSTGRES_USER};

alter role ${POSTGRES_USER}
set search_path
="$user",${SCHEMA},${STAGESCHEMA};